<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.20" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GreXml.Core\GreXml.Core.csproj" />
  </ItemGroup>

</Project>
